workflows:
  default-workflow:
    name: Default Workflow
    environment:
      groups: openweather
      flutter: stable
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/build
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - flutter packages pub get
      - mkdir -p lib/infrastructure/core/
      - echo $OPEN_WEATHER_APP_ID | base64 --decode > lib/infrastructure/core/open_weather_app_id.dart
      - find . -name "open_weather_app_id.dart"
      - find . -name "open_weather_app_id.dart" | xargs cat
      - echo $OPEN_WEATHER_APP_ID2 | base64 --decode > lib/infrastructure/core/open_weather_app_id2.dart
      - printenv
      - find . -name "open_weather_app_id2.dart"
      - find . -name "open_weather_app_id2.dart" | xargs cat
      - echo $OPEN_WEATHER_APP_ID3
      - echo $OPEN_WEATHER_APP_ID3 | base64 --decode > lib/infrastructure/core/open_weather_app_id3.dart
      - find . -name "open_weather_app_id3.dart"
      - find . -name "open_weather_app_id3.dart" | xargs cat
      - XXflutter pub run build_runner build --delete-conflicting-outputs
      - flutter test --coverage
    artifacts:
      - coverage/lcov.info